### ISSUE TITLE
doesn't work with x-camera loaded

### ISSUE THREAD

**Issue by sergiolamares** [skiselkov/StopZoomingDammit#2]
Just by loading X-Camera plugin, even with it disabled on X-Plane, SZD doesn't work. I had to "remove" X-camera to get SZD working

**Comment by skiselkov** [comment]
SZD isn't compatible with X-Camera, that is a known issue. Plugin enable/disable is a soft function in X-Plane and it's up to the plugin to honor it (and X-Camera doesn't).
